// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpAnhrErDpFXrmllGOUTAqlUQnzGpo7s',
    appId: '1:400645385268:web:1afa1d3ec4427867b5ae61',
    messagingSenderId: '400645385268',
    projectId: 'mimir-1a487',
    authDomain: 'mimir-1a487.firebaseapp.com',
    storageBucket: 'mimir-1a487.firebasestorage.app',
    measurementId: 'G-KS7BWXS5HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM79n1EwMztZVuh1GDAQUtF_IkfCWBHAA',
    appId: '1:400645385268:android:f966c1b7d5d9d8e0b5ae61',
    messagingSenderId: '400645385268',
    projectId: 'mimir-1a487',
    storageBucket: 'mimir-1a487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbRptDQY-0NbrbsI9WOWKDPAfAWdKd0o4',
    appId: '1:400645385268:ios:9e6d46c058a48fc9b5ae61',
    messagingSenderId: '400645385268',
    projectId: 'mimir-1a487',
    storageBucket: 'mimir-1a487.firebasestorage.app',
    iosBundleId: 'com.example.webPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbRptDQY-0NbrbsI9WOWKDPAfAWdKd0o4',
    appId: '1:400645385268:ios:9e6d46c058a48fc9b5ae61',
    messagingSenderId: '400645385268',
    projectId: 'mimir-1a487',
    storageBucket: 'mimir-1a487.firebasestorage.app',
    iosBundleId: 'com.example.webPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcpAnhrErDpFXrmllGOUTAqlUQnzGpo7s',
    appId: '1:400645385268:web:dd31dfc48467ca3cb5ae61',
    messagingSenderId: '400645385268',
    projectId: 'mimir-1a487',
    authDomain: 'mimir-1a487.firebaseapp.com',
    storageBucket: 'mimir-1a487.firebasestorage.app',
    measurementId: 'G-NTMK6Q98PQ',
  );

}